### PR TITLE
[exercise-manager] Exercise, ExerciseMap, ExerciseCreationGUI completed

### PR DESCRIPTION
**Pull request by penguinc00kies**
This feature is for the User to create an Exercise and for the Exercise to be added to an ExerciseMap object that stores all the Exercises created by all the Users. All four layers of clean architecture were created. The final product is a screen that allows the user to create an exercise and add it to their hidden list of exercises. The program will only allow users to use exercises they made. This pull request is supposed to be linked with issue number 11. https://github.com/CSC207-2022F-UofT/course-project-fitpredict/issues/11

### CODE REVIEW

**Review by elsiezhu — CHANGES_REQUESTED** [review]
Hi Jamie,

Great implementation of Exercise, ExerciseMap, and ExerciseCreationGUI so far! Here are some suggestions/comments that I have about your code:

- Add docstrings to classes explaining their purpose/attributes/methods
- In `Exercise.java`, for `setCaloriesBurntPerMin()`, the argument is a float, but the attribute `caloriesBurntPerMin` is a double - In an in-person meeting, I remember we discussed changing all floats to doubles, so this may have been one that was missed
- There is some redundancy in `ExerciseFactory.java` and `ExerciseManager.java`, which both have `create()` methods that initialize new Exercise instances
- in `ExerciseMap.java`, the `addExercise()` method is a void method, but the docstring specifies that it returns an Exercise

Other than this, the code looks great! Good work!

**Review by DinaLojpur — CHANGES_REQUESTED** [review]
Hello Jamie! Your code looks great. I just have a couple of suggestions:
- Overall, try to add more docstrings to your methods. It'll make it easier to quickly skim your files and understand what the methods are doing.

In src/main/java/exercise/Exercise.java:
1. The caloriesBurntPerMin has double as its data type. However, in the setCaloriesBurntPerMin() method, you have caloriesBurntPerMin being passed in as a float.

In src/main/java/exercise/ExerciseTest.java:
1. You have a comment saying "do not do this..." with some code underneath. You might want to remove that code and comment and continue to write tests following the format in the lower part of the ExerciseTest method.

In src/main/java/exercise_screens/ResultScreen.java:
1. There is some code commented out at the bottom of this file. If it is not being used, consider removing it.

Great job with the clean architecture aspect Jamie!

**Review by selintasman — CHANGES_REQUESTED** [review]
Hi Jamie! Your code looks well-implemented so far! A few suggestions/comments that I have are:
- You should consider adding more docstrings to your code so that it is easier to understand what your functions are doing. 
- I have one naming suggestion. In your ExerciseCreationController.java, instead of using eib for your argument's name, I would change it to exerciseInputBoundary.
- Good Job for putting your screens  in a different package , it will be much easier when we refactor our code later!
- There are a few data type inconsistencies. In Exercise.java you initialized caloriesBurtnPerMin as a double but in setCaloriesBurntPerMin you are passing it as a float. Please consider changing it.
- In ExerciseCreationInteractor.java, and ResultScreen.java there is some code that is commented (I believe it is an old version?) It would be best if you deleted them, if you are not planning on using them at a later time.
- Lastly,  you have created an ExerciseTest class to test your code, but I think it would be better if you have implemented it in a Test file.

Good Job!!

**Comment by penguinc00kies** [comment]
Hello everybody, 

I have modified my code in accordance with your comments. Docstrings have been added, redundant classes have been deleted, and data type inconsistencies have been rectified. I am choosing to keep my commented code for now since I need it just in case my current code doesn't work after it has been merged with the User class. Thanks for the feedback!

**Review by elsiezhu — DISMISSED** [review]

**Review by selintasman — DISMISSED** [review]
Hi Jamie! Thank you for the changes. Everything looks good to me!

**Review by DinaLojpur — DISMISSED** [review]
Your changes approved!

**Pull request merged**
