### PR TITLE
[refactor-fix-currentuser-tests] fixed tests for CurrentUser

### LINKED ISSUE #54: refactor-fix-currentuser-tests
This issue is to fix the NullPointerError within `CurrentUserTest`

### PR DESCRIPTION
**Pull request by VangoCode**
This is a pull request to fix the CurrentUser tests, as we have decided on a new way of logging in a user.

Since this pull request is quite simple, there is no point in adding a list of changes. The only change was in `src/test/java/UserLogin/CurrentUserTest.java`

### CODE REVIEW

**Review by selintasman — DISMISSED** [review]
Thank you Ron for the changes! Approved!

**Review by selintasman — APPROVED** [review]
Approved!

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by AubreyNadler — APPROVED** [review]
Looks good

**Pull request merged**
