### PR TITLE
[refactor-display-zoom-test-suite] DataPointManager.java, DataPointMapTest.java, DataPointTest.java implemented

### LINKED ISSUE #29: refactor-display-zoom-test-suite
This feature is for implementing the empty tests in `DataPointTest.java`, `DataPointMapTest.java`, and `DataPointManagerTest.java`.

### PR DESCRIPTION
**Pull request by elsiezhu**
Implemented test suite for `display-zoom`. This was completed in the files: `DataPointTest.java`, `DataPointMapTest.java`, and `DataPointManagerTest.java`. Wrote comprehensive tests for helper functions and most setter functions in `DataPoint`, `DataPointMap`, and `DataPointManager` classes. I chose not to write tests for most getter functions since they are single-line functions that were generated by IntelliJ.

### CODE REVIEW

**Review by VangoCode — APPROVED** [review]
looks good! approved

**Review by AubreyNadler — APPROVED** [review]
Looks good! Approved.

**Review by DinaLojpur — APPROVED** [review]
Looks good. Approved!

**Review by selintasman — APPROVED** [review]
Hey Elsie! The tests look good to me! Approved.

**Pull request merged**
