### PR TITLE
[clean-up-comments-and-code] Clean up the comments & Code

### LINKED ISSUE #82: clean-up-comments-and code
Before our final submission, this branch is for any group members to clean up their code and delete any useless comments. There are no functional changes in this branch.

### PR DESCRIPTION
**Pull request by VangoCode**
This pull request is to address the issue of some missing documentation and remove unnecessary code/comments. Since this was an issue worked on by everyone, there is no need for an in-depth breakdown of the changelog. Essentially, everyone just removed unused code, added some documentation, and/or removed redundant comments.

### CODE REVIEW

**Review by selintasman — DISMISSED** [review]
Good Job everyone!! We are done! Approved!!

**Review by AubreyNadler — APPROVED** [review]
Good Work Everyone!!

**Review by selintasman — APPROVED** [review]
Good Job everyone!! We are done :)

**Review by elsiezhu — APPROVED** [review]
Great job everyone! :)

**Pull request merged**
