### PR TITLE
[integrate-screens-into-one-gui] Fixed issue with UserAccountLists not writing to accounts.ser

### PR DESCRIPTION
**Pull request by penguinc00kies**
After merging the screens, there was an issue with the User class where it was no longer serializable because it instantiated a DataPointMap immediately when a new User was instantiated. Now, a User instance's DataPointMap will be instantiated upon a getDataPointMap() call. This does come with the unfortunate drawback that a User's DataPointMap cannot be saved across multiple launches of the program. There was also an oversight in UserCreationScreen where newly created Users were not being added to accounts.ser. That issue has also been rectified.

### CODE REVIEW

**Review by selintasman — APPROVED** [review]
Thank you for all the changes Jamie! Everything looks good! Approved!

**Comment by AubreyNadler** [comment]
this means a user will have to input all previously inputted DataPoints every time they run the program?

**Review by elsiezhu — APPROVED** [review]
Changes look good! Thanks for catching this!

**Review by AubreyNadler — APPROVED** [review]
All good, approved.

**Pull request merged**
