### PR TITLE
[refactor-display-view-bugs-fix] Refactor DisplayView, fix bugs

### LINKED ISSUE #24: refactor-display-view-fix-bugs
This feature is to fix bugs in the display-view feature that were encountered when merging to the main branch.

### PR DESCRIPTION
**Pull request by VangoCode**
This feature was made to fix bugs in the DisplayView function that caused compilation issues, such that the JSwing Main File did not compile. With this bug fix, it now compiles.

Changes in this pull request:
- Removed the "table_headers" string in `src/main/java/screens/Table.java`. Firstly, this does not follow our naming convention, and secondly, it breaks the table generation
- Fixed the sorting of dates in `src/main/java/screens/Table.java`. Originally, we treated `Collections.sort` as a non-mutating function, when in reality it is.
- Changed the way that `Table.generate` actually generates the table in `src/main/java/screens/Table.java`, by returning a new Object, rather than using curly brace {} notation.

### CODE REVIEW

**Comment by elsiezhu** [comment]
Bug fixes look good! Approved!

**Review by elsiezhu — APPROVED** [review]
Bug fixes look good! Approved!

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by DinaLojpur — APPROVED** [review]
Approved!

**Pull request merged**
