### PR TITLE
[user-login] UserLogin system and the UserLoginGUI are completed.

### LINKED ISSUE #2: user-login
Feature "Login" user story

### PR DESCRIPTION
**Pull request by selintasman**
This feature is for the User to log into his personal account using his username and password. 
Some classes that have been implemented are: 
- CurrentUser: This is an entity that inherits from the class User. It is null until a User logs in.
- UserAccountList: This is a list of accounts that have been created. 
- UserLogin: This is the use case that checks and logs the User in if the username actually exists in the accounts.ser file AND the inputted password matches the password in the list
- UserLoginController, UserLoginScreen and LoginScreenMain are classes for the GUI.

### CODE REVIEW

**Comment by VangoCode** [comment]
Hi Selin & Dina, I think that this feature is well done, and I have a few things to add!

Feel free to respond to any of the reviews I have written below, and if you are responding to a question posed in one of the bullet points, also add what number the point is so I can tell what is being responded to :D.

1. For the future, in your commit messages, it would be better to keep things more descriptive. What I mean is that there are some instances where the commit message would resemble `Some files were changed`, or something similar. I think that specifying _which_ files were changed would make viewing the commit history much easier, especially at a glance.
2. I don't think that we need to include the `gradle` folder, as it is just the cache. It will make our repository more difficult to follow - perhaps we can remove these from the repository, and add them to a .gitignore file, to ensure that we do not clutter the repo.
3. I think that overall, clean architecture and SOLID principles are both followed quite well. The only change (which we should all do), is to move the packages into their respective Clean Architecture layer package, (i.e entities with entities, screens with screens, etc.)
4. In `src/main/java/user_login/CurrentUser.java`, there appears to be an empty constructor - is this a necessity? The rest of the file looks great in my opinion. I like the docstrings, and the flow is easy to follow.
5. In `src/main/java/user_login/LoginScreenMain.java`, on lines 10-11, I think that before this project goes into real "production" mode, we should remove the test user, as it adds redundancy and if there is another Selin Tasman whose favourite number is 1, they will never be able to own that username.
6. In `src/main/java/user_login/User.java`, I am confused as to why there are both a `User` Constructor, and a `User` method that returns `null`? From what I can gather, they have exactly the same functionality, and as such one of them should be removed (likely the method, not the constructor).

**Comment by elsiezhu** [comment]
Hi Selin & Dina,
This feature is implemented very well! It follows Clean Architecture and the code is written well. 
A few suggestions/comments that I have about your implementation so far is:
- LoginScreenMain.java on line 10, is this meant to be for testing the Java Swing window? Since this is a hardcoded User creation. 
- In CurrentUser.java, there is an empty constructor. What is this used for/is it necessary?
- For User.java, it would be best to use the Java Date object to store birthdays, instead of a String. It would be easier to convert between dates when performing calculations, since the Java Date class can easily compare dates without having to parse through months/days/years. 
- Great docstrings for functions, helps with readability a lot!
- For UserAccountList.java, the userAccountList attribute is final, but it is mutated using the addNewUser() method. Is there a reason for this?
- For Clean Architecture and SOLID principles, we should work to refactor the code so that each package is in a Clean Architecture layer folder. 
Other than this, everything looks great! Good work so far!

**Comment by penguinc00kies** [comment]
Comment
Hey Selin and Dina,

This is overall well-written code, some things I noticed are
-the files adhere to clean architecture and SOLID principles
-docstrings are clear and consice 
-in line 10 of LoginScreenMain.java, you seem to create a "dummy" user, why is it there?
-I understand that CurrentUser.java requires an empty constructor in  User.java in order to exist, but then why does CurrentUser.java also have an empty constructor?
-why does User.java have a method nearly identical to its constructor except it has return type null on line 47?
-code is well commented in the sections where there may be ambiguity
Good work!

**Review by VangoCode — CHANGES_REQUESTED** [review]
Hi Selin & Dina, I think that this feature is well done, and I have a few things to add!

Feel free to respond to any of the reviews I have written below, and if you are responding to a question posed in one of the bullet points, also add what number the point is so I can tell what is being responded to :D.

1. For the future, in your commit messages, it would be better to keep things more descriptive. What I mean is that there are some instances where the commit message would resemble `Some files were changed`, or something similar. I think that specifying which files were changed would make viewing the commit history much easier, especially at a glance.
2. I don't think that we need to include the `gradle` folder, as it is just the cache. It will make our repository more difficult to follow - perhaps we can remove these from the repository, and add them to a .gitignore file, to ensure that we do not clutter the repo.
3. I think that overall, clean architecture and SOLID principles are both followed quite well. The only change (which we should all do), is to move the packages into their respective Clean Architecture layer package, (i.e entities with entities, screens with screens, etc.)
4. In `src/main/java/user_login/CurrentUser.java`, there appears to be an empty constructor - is this a necessity? The rest of the file looks great in my opinion. I like the docstrings, and the flow is easy to follow.
5. In `src/main/java/user_login/LoginScreenMain.java`, on lines 10-11, I think that before this project goes into real "production" mode, we should remove the test user, as it adds redundancy and if there is another Selin Tasman whose favourite number is 1, they will never be able to own that username.
6. In `src/main/java/user_login/User.java`, I am confused as to why there are both a User Constructor, and a `User` method that returns null? From what I can gather, they have exactly the same functionality, and as such one of them should be removed (likely the method, not the constructor).

**Review by penguinc00kies — CHANGES_REQUESTED** [review]
Hey Selin and Dina,

This is overall well-written code, some things I noticed are
-the files adhere to clean architecture and SOLID principles
-docstrings are clear and consice
-in line 10 of LoginScreenMain.java, you seem to create a "dummy" user, why is it there?
-I understand that CurrentUser.java requires an empty constructor in  User.java in order to exist, but then why does CurrentUser.java also have an empty constructor?
-why does User.java have a method nearly identical to its constructor except it has return type null on line 47?
-code is well commented in the sections where there may be ambiguity
Good work!

**Review by elsiezhu — CHANGES_REQUESTED** [review]
Hi Selin & Dina,

This feature is implemented very well! It follows Clean Architecture and the code is written well.

A few suggestions/comments that I have about your implementation so far is:

- LoginScreenMain.java on line 10, is this meant to be for testing the Java Swing window? Since this is a hardcoded User creation.
- In CurrentUser.java, there is an empty constructor. What is this used for/is it necessary?
- For User.java, it would be best to use the Java Date object to store birthdays, instead of a String. It would be easier to convert between dates when performing calculations, since the Java Date class can easily compare dates without having to parse through months/days/years.
- Great docstrings for functions, helps with readability a lot!
- For UserAccountList.java, the userAccountList attribute is final, but it is mutated using the addNewUser() method. Is there a reason for this?
- For Clean Architecture and SOLID principles, we should work to refactor the code so that each package is in a Clean Architecture layer folder.

Other than this, everything looks great! Good work so far!

**Comment by selintasman** [comment]
@VangoCode @elsiezhu @penguinc00kies Hello guys ! 
Thank you for all the comments! Some clarifications. The empty constructor in CurrentUser is necessary.
In UserAccountList.java, the userAccountList was initially not final but Java made a suggestion to make it final. 
Lastly, for now in LoginScreenMain, the reason there is a dummy user was for testing purposes to make sure that the LoginUseCase was working properly (since we did not merge to main yet with User-creation).
Otherwise, other changes like the duplicate User method in User.java was removed.

**Comment by VangoCode** [comment]
Hi Selin, thank you for clarifying. Upon looking at your refactors, I think all looks good. I have approved your request :D

**Review by VangoCode — DISMISSED** [review]

**Comment by elsiezhu** [comment]
Hi Selin! Thanks for clarifying! I think your feature all looks good now, I will approve your pull request.

**Comment by penguinc00kies** [comment]
Hi Selin, thank you for clarifying. Your code looks cleaner now with less redundancies. Approved!

**Review by elsiezhu — DISMISSED** [review]

**Review by penguinc00kies — DISMISSED** [review]

**Review by penguinc00kies — APPROVED** [review]
Merge request changes look good!

**Review by VangoCode — APPROVED** [review]
The merge conflict resolution looks good. Approved!

**Review by elsiezhu — APPROVED** [review]
Changes look good, pull request approved

**Pull request merged**
