### PR TITLE
[exercise-manager-user-class-integration] ExerciseCreationController and ExerciseCreationInteractor are completeed

### LINKED ISSUE #22: exercise-manager User class integration
Due to the timelines of merging to main and refactoring, I was not able to work on the exercise-manager branch with concrete implementations of User methods. Now that Exercise-related classes and User-related classes are all pushed to main, I will return to my Exercise-related classes and properly implement User-related functionality within them.

### PR DESCRIPTION
**Pull request by penguinc00kies**
All Exercise-related classes have been refactored to be compatible with CurrentUser. Code has been tidied up to include more docstrings and redundant code has been cleaned up. The code has also been edited to closer adhere to clean architecture. This was a QoL update, no functional changes were made.

### CODE REVIEW

**Review by DinaLojpur — DISMISSED** [review]
Looks good, Jamie! Approved!

**Review by AubreyNadler — DISMISSED** [review]
Looks good.

**Review by DinaLojpur — DISMISSED** [review]
Approved!

**Review by selintasman — APPROVED** [review]
Looks good Jamie! Thank you for the changes. Approved!

**Review by DinaLojpur — APPROVED** [review]
Approved!

**Review by AubreyNadler — APPROVED** [review]

**Pull request merged**
