### PR TITLE
[data-input-implementation] Data Input Feature Implemented

### LINKED ISSUE #36: data-input-implementation

### PR DESCRIPTION
**Pull request by AubreyNadler**
Classes DataInputScreen, DataInputScreenMain, DataInputController, DataInputter and inteface DataInputBoundary were all created and place in appropriate layer packages.

### CODE REVIEW

**Review by penguinc00kies — DISMISSED** [review]
Hey Aubrey, 

Thanks for getting all this done on a tight deadline, now we can finally start connecting all the individual user stories to one cohesive program in main! That said, I have some thoughts:
-not all of your methods have docstrings, please add proper docstrings
-in DataInputter.java, it seems that you're creating DataPoint objects using the DataPoint constructor; I think it would be better to use Elsie's DataPointManager.java to accomplish this task since it even checks for invalid parameters (I know it would be a use case calling another use case but I think an exception could be made)
-I see that Dashboard.java is virtually empty, is the class supposed to be deleted or is there a reason you're keeping the file?
-please create test files if applicable, and remember to fill in the test coverage doc Elsie shared with you as that's part of our Milestone 4 mark

Otherwise, everything looks squeaky clean! Good job adhering to clean architecture.

**Review by DinaLojpur — APPROVED** [review]
Everything looks good! Approved!

**Review by penguinc00kies — APPROVED** [review]
Looks good now, approved!

**Review by selintasman — APPROVED** [review]
Thank you for the changes Aubrey! Looks good!

**Review by elsiezhu — APPROVED** [review]
Changes look good, approved!

**Review by VangoCode — APPROVED** [review]
Looks good! Approved

**Pull request merged**
