### PR TITLE
[refactor-display-view-fix-table] Fixed table not showing, added predictions

### LINKED ISSUE #64: refactor-display-view-fix-table
This issue was created to fix the issue of the table not showing up/properly performing predictions on the user's data.

### PR DESCRIPTION
**Pull request by VangoCode**
Hey everyone! This pull request is to fix the table not showing up in our main JSwing file, and to add prediction functionality when you press the predict button.

Notes:
- Created a DashboardController to update the Dashboard's predictions, while adhering to Clean Architecture
- Updated `src/main/java/entities/DataPoint.java` to take an overloaded constructor as a Date object, rather than just day/month/year
- Updated `src/main/java/screens/DashboardScreen.java` so that whenever you load the screen, it generates predictions and updates the display before creating it
- Updated `src/main/java/screens/MainMenuScreen.java` to include the new DashboardController
- Updated `src/main/java/use_cases/DataPointManager.java` to overload `createDataPoint` to take a Date object, rather than just day/month/year
- Added caloriePredictions to `src/main/java/use_cases/PredictManager.java`
- Created `src/main/java/use_cases/UpdatePredictions.java`, a new Use Case that deals with updating the predictions
- Updated `src/test/java/predictor/PredictManagerTest.java` to reflect the new calorie prediction method with tests

### CODE REVIEW

**Review by DinaLojpur — APPROVED** [review]
Looks good!

**Review by penguinc00kies — APPROVED** [review]
Looks great, thanks so much for getting this working!

**Review by AubreyNadler — APPROVED** [review]
Great job, approved

**Review by selintasman — APPROVED** [review]
Looks good! Great Job! Approved!

**Review by elsiezhu — APPROVED** [review]
Changes look good! Approved!

**Pull request merged**
