### PR TITLE
[refactor user login and add tests]

### LINKED ISSUE #32: refactor-user-login-and-add-tests

### PR DESCRIPTION
**Pull request by selintasman**
Hello I have fixed a bug in UserLogin use case and implemented a few test cases!

### CODE REVIEW

**Review by DinaLojpur — DISMISSED** [review]
Approved!

**Review by penguinc00kies — CHANGES_REQUESTED** [review]
Hey Selin,
Good work on these tests! One thing though, please add a @Before setup method when you're instantiating new objects outside the tests.

**Review by elsiezhu — DISMISSED** [review]
Hi Selin, changes look good! Approved!

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by elsiezhu — APPROVED** [review]
Looks good Selin! approved!

**Review by VangoCode — APPROVED** [review]
Looks good Selin, approved!

**Pull request merged**
