### PR TITLE
[refactor-data-predict-implement-predictmanager-tests] Implement tests & Bugfixes

### LINKED ISSUE #49: refactor-data-predict-implement-predictmanager-tests
This refactor is to implement the tests for the PredictManager class.

### PR DESCRIPTION
**Pull request by VangoCode**
Hi! There are a number of things to outline in this pull request:

- All features that interact with the `CurrentUser.getInstance()` method have been changed to now use `CurrentUser.getInstance.getUser()`. This is because `CurrentUser.getInstance()` either creates an instance of `CurrentUser` or returns the `CurrentUser` instance, if applicable. `CurrentUser`'s instance then needs to use `CurrentUser.getUser()` in order to actually get the information about the current instance's user that has been set with `CurrentUser.getInstance().setUser()`.
- `src/main/java/entities/CurrentUser.java`'s constructor has been changed, as the `super()` call in its main constructor has `height` and `weight` in swapped order.
- "`null` checks" have been implemented for both `src/main/java/use_cases/BMIPredictor.java` and `src/main/java/use_cases/WeightPredictor.java`, as it was causing a nullPointerError in some of the tests. It is simply testing that the parameter passed in is not null.
- An extra case has been added to `src/main/java/use_cases/CaloriePredictor.java` to avoid divide by zero errors.
- `src/test/java/predictor/BMIPredictorTest.java` and `src/test/java/predictor/WeightPredictorTest.java` have both been changed to properly reflect the way that their respective Predict functions work, i.e checking for tomorrow's prediction.
- Redundant test case has been removed from `src/test/java/predictor/WeightPredictorTest.java`
- Threshold/delta values have been added to `src/test/java/predictor/CaloriePredictorTest.java`, `src/test/java/predictor/WeightPredictorTest.java`, and `src/test/java/predictor/BMIPredictorTest.java`  to avoid floating point/rounding errors resulting in failed test cases
- `src/test/java/predictor/PredictManagerTest.java` has been completely implemented, and passes all test cases using PredictManager to call its respective Predictor classes.
- `src/test/java/tutorial/HelloWorldTest.java` has been removed, as it is an unnecessary fragment left over from the tutorial that causes our autograder to fail

### CODE REVIEW

**Review by penguinc00kies — APPROVED** [review]
Thanks for discovering this Ron! Your changes look good, I'll be sure to update my code too.

**Review by selintasman — APPROVED** [review]
Hi Ron! Thank you for making all the changes! Great Work! Approved.

**Review by AubreyNadler — APPROVED** [review]
Looks good although the CurrentUser.getInstance().getUser().getUsername() changes are unnecessary as CurrentUser.getUsername() overrides User.getUsername() which calls getUser() inside. You can change it back if you want it has no effect.

**Comment by VangoCode** [comment]
> Looks good although the CurrentUser.getInstance().getUser().getUsername() changes are unnecessary as CurrentUser.getUsername() overrides User.getUsername() which calls getUser() inside. You can change it back if you want it has no effect.

Hi Aubrey, although I see what you mean, I think that it technically does have an effect. `CurrentUser.getUsername()` is a regular method, so you would need to create a `CurrentUser` object to actually use it. Our new way of accessing the current user, using `CurrentUser.getInstance().getUser().getUsername()` gets this current user using a static method, thus it leads to the same user across different files. For `CurrentUser.getUsername()` to be equivalent, we would need to change its return value to `getInstance.getUser.getUsername()`.

**Pull request merged**
