### PR TITLE
[data-predict-body-implementation] WeightPredictor and BMIPredictor

### LINKED ISSUE #18: data-predict-body-implementation
Due to an unexpected situation, the data-predict feature was not implemented in full. This issue is to rectify this, by ensuring that the prediction algorithms are fully written out (i.e, the to-dos are filled in).
The original issue has been split into this one. You can view the completed portion at #17

### PR DESCRIPTION
**Pull request by AubreyNadler**
WeightPredictor.predict and BMIPredictor.predict are implemented and some import are fixed in the prediction test classes

### CODE REVIEW

**Review by penguinc00kies — CHANGES_REQUESTED** [review]
Hey Aubrey, 

This is looking great and overall well-written. I have some thoughts:
-great adherence to clean architecture
-I believe Paul once said "You write comments to explain _why_ your code is doing something, not _what_ it's doing", I think you have some redundant comments like at line 36 of BMIPredictor.java
-I don't think you've filled any of the test cases in for WeightPredictorTest.java, please complete them as well as fill in the milestone 4 test coverage doc Elsie shared with the group and explain what your tests are covering
-in WeightPredictor.java, the return statement in line 52 is identical to the "placeholder" return statement in line 32 of the previous iteration of the file, I'm pretty sure this is all corrct but I just want to double check with you that it is
Otherwise, good work!

**Review by elsiezhu — CHANGES_REQUESTED** [review]
Hi Aubrey,

I looked over your implementation for the Prediction classes. Good work so far! I have a few suggestions/comments for you about your implementation:

- in all the Predictor classes, I see that predictions will be generated from a startDate to the present time. If you take a look into the DataPoint class, you will see that the Date attribute of a DataPoint will always be initialized to 12:00AM on a particular day. In other words, DataPoint does not support time -- only date. This is because when we want to merge attributes such as BMI, weight, etc., we do not want to add a layer of complexity (because when we compare Date objects, comparison methods will return False if hour/minute/second do not match, even if month/day/year do). Thus, you will have to make some changes your implementation to match this, as we want to keep dates uniform throughout the project. 
- I see some redundancy in your code for getting/iterating through dates as well as putting values into the HashMap, where those lines of code are the same throughout every child of Predictor. I would suggest to make this a helper function.
- Just a gentle reminder to implement the tests fully later - not sure if you or @VangoCode will be doing this.
- good use of comments! Makes the code easy to follow.

Other than this, the code looks good! Please let me know if you need further explaining for my first suggestion.

**Review by VangoCode — DISMISSED** [review]
Hi @AubreyNadler , overall, I think that this code is very well written. I just have a few comments/requests:
1. There is good adherence to SOLID principles and clean architecture throughout the functions
2. Ensure that the comments are more meaningful - right now they are mostly saying _what_ the code is doing, but it is better for maintainability if you state _why_ you did some line of code, for instance, answering "why did I convert the date to milliseconds?"
3. The WeightPredictorTest test file is not implemented. I have already implemented BMIPredictorTest and CaloriePredictorTest, but this one needs to be written.

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by selintasman — APPROVED** [review]
Hey Aubrey, thank you for making the changes! They look good to me! Approved.

**Review by elsiezhu — APPROVED** [review]
Changes look good, approved!

**Pull request merged**
