### PR TITLE
Comment exercise code and rename exercise tests

### LINKED ISSUE #68: comment-exercise-code-and-rename-exercise-tests
Adding comments to Exercise-related classes and renaming test methods in Exercise-related tests to make the code overall more readable to an outside party.

### PR DESCRIPTION
**Pull request by penguinc00kies**
Added comments to relevant Exercise-related classes and renamed test methods in Exercise-related tests to be consistent with "testCamelCase" pattern. Done for the sake of future readibility.

### CODE REVIEW

**Comment by VangoCode** [comment]
Hi Jamie, would you be able to rename all of the tests to follow the same naming convention (including mine and Aubrey's)? Thanks so much :D

**Comment by penguinc00kies** [comment]
On it! 👍

**Review by VangoCode — APPROVED** [review]
Thanketh thy changes, Jamie.  Looks exquisite!

**Review by elsiezhu — APPROVED** [review]
Changes look good, Jamie! Approved!

**Review by selintasman — APPROVED** [review]
Thanks for the changes Jamie! Approved!

**Review by DinaLojpur — APPROVED** [review]
Looks good bud!

**Pull request merged**
