### PR TITLE
[update-readme] README.md is updated with instructions on how to run and use program files

### LINKED ISSUE #41: update-readme
Write and update `README.md` with description of the project

### PR DESCRIPTION
**Pull request by elsiezhu**
The repository's `README.md` is updated with detailed instructions on how to open, run, and use the program's files. 

I have included images of screenshots of the UI screens to make it easier for the reader to understand how to use it. These can be found and accessed from the `images` folder.

However, since we still have a few bug fixes to complete in #50, I have not yet added anything in the `README.md` about how to use the Prediction screen and table, since this screen is not fully functional yet. This will be done in another issue that I will open once we complete these bug fixes.

### CODE REVIEW

**Review by penguinc00kies — DISMISSED** [review]
Looks beautiful, approved!

**Review by AubreyNadler — CHANGES_REQUESTED** [review]
Very good! You just missed a 'Y' on line 33 birthday in the readme

**Review by penguinc00kies — APPROVED** [review]
Still looks great, approved!

**Comment by elsiezhu** [comment]
@AubreyNadler Fixed it, please look over the changes again

**Review by VangoCode — APPROVED** [review]
Looks amazing!! Very good use of Markdown features. Approved

**Review by AubreyNadler — APPROVED** [review]
Looks great!

**Review by selintasman — APPROVED** [review]
Looks very good! Approved!

**Pull request merged**
