### PR TITLE
[data-input-bug-fix] Refactoring and fixing bugs in DataInput methods

### LINKED ISSUE #57: data-input-bug-fix
Fixing the bug that null is printed every time data is inputted

### PR DESCRIPTION
**Pull request by AubreyNadler**
- There was a line left in my inputDataResult method that I used when I was implementing that was causing null to be printed every time data was inputted. It has been removed. 
- I have refactored a part of DataInputter.inputData to make it cleaner.
- Instead of displaying an error message when a user tries to input data for a day that they previously inputted for, it updates the datapoint and alerts the user
- Alerts the user if the input data is invalid

### CODE REVIEW

**Review by VangoCode — DISMISSED** [review]
Hi Aubrey, can you confirm that the DataInput code is working as required? Why is the `getDataPoint()` method returning null?

**Comment by AubreyNadler** [comment]
It should be null when a new day is inputted since getDataPoint() returns null if im searching for a day that is not in the datapointmap

**Review by elsiezhu — DISMISSED** [review]
Hi Aubrey,

I have a couple of questions/comments to make about the DataInput feature:

- Can you confirm that there was no other issue with the Data Input Screen that would cause 'null' to be printed? Such as issues with creating DataPoints/adding to the DataPointMap with the inputs?
- In `DataInputScreen.java`, I see that when inputting data, before that DataPoint is added to the DataPointMap, there is a check to see if data for that date already exists - and creates an error screen if it does. In `DataPointMap.addDataPoint()`, `HashMap.put()` is called. This adds the specified key/value pair to the HashMap, and **replaces** the old value associated with that key if the key is already in the HashMap. So, it is a little redundant to check for this, since it will not cause an exception to be thrown and it allows a user to edit their old data.

**Comment by VangoCode** [comment]
> It should be null when a new day is inputted since getDataPoint() returns null if im searching for a day that is not in the datapointmap

Ah, okay I see. Thanks so much for clarifying.

**Review by penguinc00kies — DISMISSED** [review]
Looks good after the changes, approved!

**Review by elsiezhu — DISMISSED** [review]
Changes look good, approved

**Review by DinaLojpur — DISMISSED** [review]
Looks good!

**Review by penguinc00kies — DISMISSED** [review]
Looks good, to avoid the current merge conflict in this branch, can you go delete RegisteredAccountsList.ser? It doesn't exist in our Main anymore so you can safely get rid of it in this branch.

**Review by selintasman — DISMISSED** [review]
Hey Aubrey, everything looks good but I think it would be best if you completly deleted the RegisteredAccountsList.ser file.

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by DinaLojpur — APPROVED** [review]
Approved!

**Review by elsiezhu — APPROVED** [review]
Changes look good!

**Pull request merged**
