### PR TITLE
[refactor-datapoint-tests] Refactored tests for DataPoint, DataPointMap, and DataPointManager

### LINKED ISSUE #56: refactor-datapoint-tests
Refactor test suite for `DataPoint`, `DataPointMap`, and `DataPointManager`. A number of tests are currently failing, so either the tests or the original code. Will also add more comprehensive testing.

### PR DESCRIPTION
**Pull request by elsiezhu**
Refactored the test suites for `DataPoint`, `DataPointMap`, and `DataPointManager`. 

Many of the tests in `DataPointTest.java`, `DataPointMapTest.java`, and `DataPointManagerTest.java` were failing, so I investigated why they were failing, and fixed either the tests or the code, depending on which was necessary. 

Also, more comprehensive testing was written, including tests for:

- Getter and setter methods in `DataPoint`
- Getter methods in `DataPointMap`
- Checking for proper exceptions thrown by methods in `DataPointManager`

All tests in the 3 test suites should now pass when run. Also, these tests **must** be run through IntelliJ IDEA, and **not** Gradle.

### CODE REVIEW

**Review by VangoCode — APPROVED** [review]
Looks good Elsie, thanks for fixing up the tests!

**Review by AubreyNadler — COMMENTED** [review]
Are your tests running and passing? I ask because a few of us have experienced issues with the @Before and @After methods.

**Review by AubreyNadler — APPROVED** [review]
Ok. Looks Good

**Comment by AubreyNadler** [comment]
oops

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Pull request merged**
