### PR TITLE
[display-zoom] DataPoint, DataPointMap, DataPointManager completed

### LINKED ISSUE #5: display-zoom
Feature “Zoom in on specific graph points” user story

### PR DESCRIPTION
**Pull request by elsiezhu**
DataPoint, DataPointMap, DataPointManager classes have been implemented in the DisplayZoom package. 
`DataPoint` is an entity - it stores various fitness stats as attributes for a given calendar date. It has getter and setter methods for each attribute, as well as helper functions. 
`DataPointMap` is a use case - it stores a HashMap object that maps Date objects to DataPoint objects. Each User has a unique instance of DataPointMap. It has getter and setter functions, as well as a `mergeDataPoints()` method, which merges a HashMap of Date objects mapped to DataPoint objects with its dataPointMap attribute. 
`DataPointManager` is a use case - it is the manager class for DataPoint. It has a `createDataPoint()` method, which initializes a DataPoint object after checking for valid arguments. 
I have also written test suites for each of these classes, which are in `DataPointTest.java`, `DataPointMapTest.java`, `DataPointManagerTest.java`, but the tests have yet to be populated.

### CODE REVIEW

**Review by VangoCode — CHANGES_REQUESTED** [review]
Hi Elsie, overall this is written very well. There are a few things that I will change, however.

1. In your docstrings, I would make the documentation match more to the course examples. What I mean is by adding @param functions, and using /** ... */ comments rather than /* ... */ comments
2. This is a more general thing that we need to fix during refactoring, but there is no link between the logged-in User's DataPointMap. Since you are not working on the User feature, it is not a change you can make, but it is a note that I leave here for us to refactor after we merge.
3. I believe that there should be some sort of boundary within the `DataPointManager.createDataPoint()` method. I see that you are throwing illegal argument exceptions based on invalid data, but I believe that according to Clean Architecture, there should be some sort of InputBoundary to check. At the very least, it should be in a separate helper method, as this does not currently follow the Single Responsibility Principle, as `DataPointManager.createDataPoint()` has multiple responsibilities
4. Once again, after merging, we will need to add a few extra functions for merging DataPointMaps, similar to `DataPointMap.mergeDataPoints`. Specifically, we will need to merge Weight and BMI predictions.

**Review by DinaLojpur — CHANGES_REQUESTED** [review]
Hello Elsie! Great job on your code. I just have a couple of suggestions. In src/main/java/DisplayZoom/DataPoint.java:
1. For your docstrings, instead of doing "/*" (which is meant for multi-line comments), try "/**" instead (which is meant for docstrings)
2. Instead of having weight as a float, you might want to use the data type double instead. The User entity has weight listed as a double and it will be better if we try to retain the same variable data types across all files.

In src/test/java/DisplayZoom/DataPointManagerTest.java and src/test/java/DisplayZoom/DataPointMapTest.java:
1. All the tests are set to void and are not being implemented. Just remember to add some tests when you have the time!

**Review by selintasman — CHANGES_REQUESTED** [review]
Hi Elsie! This feature is implemented very well! 
A few comments/ questions that I have are:
- In DataPoint.java I believe it would be better if you used double for weight and caloriesBurnt instead of float to keep it consistent with the Exercise and User entities.
- I am confused as to why you have chosen to use Epoch. Is there a particular reason?
- I believe it would be better if you modified your docstrings (i.e use @param and /**)
- In DataPointMap.java there seems to be an empty constructor (public DataPointMap(ArrayList<DataPoint> dataPoints) {
    }) is there a reason why it is there?
- Lastly, I am not entirely sure about this so please take it with a grain of salt :) In DataPointManager.java, we are throwing a lot of exceptions regarding the validity of the arguments, but in lecture it was said that we should not be throwing exceptions for things that we expect will happen often (in this case putting in an invalid month for example).

Good Work!

**Comment by elsiezhu** [comment]
@VangoCode @selintasman @DinaLojpur Hi everyone! 
Thank you guys for all the suggestions/comments. I have made some changes - namely with docstrings, changing all floats to doubles, deleting unnecessary empty constructor for DataPointMap and adding a helper function to check for invalid inputs. I will also make a few clarifications:
- I chose to use Epoch time for DataPoint Date because the constructor with inputs (month, day, year) for Java Date is deprecated. The only remaining constructor is for Epoch. 
- For DataPointManager.java, I decided to add a helper function that would check for valid inputs, since inputting an invalid month/day/year shouldn't be very common. 
- I also do not have a Controller or Input Boundary, since my feature does not directly interact with the UI - but the data-input feature should be implementing the interaction between DataPoint and the UI.

Please take a look at my changes and let me know if there are any other issues/suggestions!

**Review by VangoCode — DISMISSED** [review]
Hi @elsiezhu , thanks for your clarifications. Your changes all look good to me as well. Approved!

**Review by VangoCode — APPROVED** [review]
@elsiezhu sorry for accidentally solving your merge conflict, I meant to solve my own 😅 re-approved!

**Review by selintasman — APPROVED** [review]
Hi @elsiezhu thank you for the clarifications and changes!

**Review by DinaLojpur — APPROVED** [review]
All the changes look good!

**Pull request merged**
