### PR TITLE
[refactor-user-creator]

### LINKED ISSUE #31: refactor-user-creator
There are some bugs in my code that I need to fix and I must add test cases.

### PR DESCRIPTION
**Pull request by DinaLojpur**
I have fixed the bug in UserCreator. I have added tests for the User entity and UserCreator use case!

### CODE REVIEW

**Review by elsiezhu — DISMISSED** [review]
Hey Dina, the changes look good! Request approved!

**Review by selintasman — DISMISSED** [review]
Hi Dina! It looks good to me.

**Review by AubreyNadler — CHANGES_REQUESTED** [review]
Good Work! Only fix needed is UserCreatorInvalidUsername test. Username given is not invalid and comment is not for the right test.

**Review by AubreyNadler — APPROVED** [review]
Good Job! Approved.

**Review by elsiezhu — APPROVED** [review]
Changes look good! approved!

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Pull request merged**
