### PR TITLE
Integrate screens into one gui

### LINKED ISSUE #40: integrate-screens-into-one-GUI
This feature is to connect all the separate screens so that they can lead into one another. All the screens will be linked in a fashion that forms a cohesive program. Any screens that are JPanels will have to be made into JFrames.

### PR DESCRIPTION
**Pull request by penguinc00kies**
This feature is to connect all the separate screens so that they can lead into one another. All the screens will be linked in a fashion that forms a cohesive program. Any screens that are JPanels will have to be made into JFrames.

### CODE REVIEW

**Review by DinaLojpur — DISMISSED** [review]
Looks good, bud. Approved!

**Review by VangoCode — DISMISSED** [review]
Looks good! (literally, because it's the GUI 😆)

**Review by AubreyNadler — CHANGES_REQUESTED** [review]
- Great adherence to clean architecture and SOLID! 
- The table doesn't show up when predictions are run.
- Line 38 of DataInputScreen you put cm for weight, please fix that.
- UI looks great, good job connecting all the screens together.
- Thanks for making your changes for the CurrentUser.getInstance() bug.

**Review by AubreyNadler — APPROVED** [review]
Looks great

**Review by DinaLojpur — APPROVED** [review]
Approved!

**Review by selintasman — APPROVED** [review]
It looks very good Jamie!! Approved!

**Pull request merged**
