### PR TITLE
[display-view] Dashboard, DashboardScreen, Table implemented

### LINKED ISSUE #8: display-view
Feature “View Dashboard/Graphs” user story

### PR DESCRIPTION
**Pull request by elsiezhu**
Implemented this feature with @VangoCode . This feature is for the user to be able to view their data. Currently, for the Minimum Viable Product, we are only implementing the Table class. The other classes have skeleton structures completed, which we implement, time permitting.

### CODE REVIEW

**Review by selintasman — CHANGES_REQUESTED** [review]
Hi @elsiezhu and @VangoCode! Everything looks good to me so far. 
I only have one question. Even though it is commented out right now but in Dashboard.java, shouldn't the argument User actually be a CurrentUser since the type of User that we are talking about is the user that is currently logged in.
Thank you!

**Review by DinaLojpur — CHANGES_REQUESTED** [review]
Hello Elsie and Ron! The code looks great so far. 

I just have one thing to mention, in src/main/java/DisplayView/Dashboard.java, you are importing user from user_login, then in the Dashboard method you are using user from the User entity. It might be better if you used currentUser from the CurrentUser entity instead. currentUser will be the user that is currently logged in and the one using the dashboard. 

Great work guys!

**Comment by VangoCode** [comment]
Hi @selintasman @DinaLojpur , I have made the changes that you requested. Please let me know if there are any other questions/changes needed!

**Review by DinaLojpur — DISMISSED** [review]
All the changes look good!

**Review by selintasman — DISMISSED** [review]
Hi Ron and Elsie, thank you for the changes!

**Review by AubreyNadler — APPROVED** [review]
Great work! Everything looks good.

**Review by AubreyNadler — CHANGES_REQUESTED** [review]
Great work! Everything looks good. Just make ScatterGraph extend Graph.

**Review by selintasman — APPROVED** [review]
All changes look good!

**Review by AubreyNadler — CHANGES_REQUESTED** [review]
Looks good. Just make ScatterGraph extend Graph.

**Review by DinaLojpur — APPROVED** [review]
All changes look good!

**Review by AubreyNadler — APPROVED** [review]
Great Work!

**Pull request merged**
