### PR TITLE
[data-input-invalid-data-checks] added checks for illegal input to weight and exercises to input data

### LINKED ISSUE #70: data-input-invalid-data-checks
Increasing checks for invalid data inputs and showing error messages.

### PR DESCRIPTION
**Pull request by AubreyNadler**
There is now one error screen for invalid date or weight. There is another for invalid exercise inputs. This will come up if an exercise that is not in the exercise map is inputted or if the exercise names list is a different size than the exercise  times list. To do this, DataInputController.inputData now returns a boolean instead of void. Also a bug when multiple exercises were inputted it would have 0 calories burned was fixed.

### CODE REVIEW

**Review by penguinc00kies — APPROVED** [review]
Looks good, approved!

**Review by DinaLojpur — APPROVED** [review]
Looks good!

**Review by selintasman — APPROVED** [review]
Hi Aubrey, looks good! Approved!

**Review by VangoCode — APPROVED** [review]
Looks good, Aubrey! Approved 💪

**Pull request merged**
