### PR TITLE
[user-creation] UserCreator system and the corresponding screen are completed.

### LINKED ISSUE #1: user-creation
Feature: "Account creation” user story

### PR DESCRIPTION
**Pull request by DinaLojpur**
This feature is for the User to create an account and enter all required personal information. All four layers of clean architecture were created. The user will use the pop up screen and fill in all their personal and account information to create an account. This account is then stored in a .ser file, which is can be accessed when logging in. The program allows anyone to create an account, if the filled-in information is deemed valid.

### CODE REVIEW

**Review by VangoCode — CHANGES_REQUESTED** [review]
Hi Dina, overall this feature was very well done! There are just a few things that I would like to comment on/request changes for:

1. The `.idea/` folder should not be included in the VCS system (in our case, Git). I would remove this, and it can be removed by temporarily deleting the `.idea/` folder, and then pushing this to Git, and then adding `.idea/*` to your `.gitignore` file. It's quite convoluted but it'll keep our repository clean.
2. I made this same comment for Selin's code, and we will all do it to our respective code, but we must repackage the files to fit into Clean Architecture (i.e, entities package for entities, etc.)
3. In `src/main/java/user_creator/User.java`, why is there an empty `User` constructor?
4. In `src/main/java/user_creator/UserCreator.java`, would you be able to comment _why_ the nested if statement is necessary? I am quite lost as to what it is doing, and a brief comment explanation will make this much more maintainable in the future.

**Review by elsiezhu — CHANGES_REQUESTED** [review]
Hi Dina,

Great implementation so far for UserCreator and its corresponding screen! Here are some suggestions/comments I would like to make to your code:

- For User.java, it would be best to use the Java Date object to store birthdays, instead of a String. It would be easier to convert between dates when performing calculations, since the Java Date class can easily compare dates without having to parse through months/days/years.
- For UserAccountList.java, the userAccountList attribute is final, but it is mutated using the addNewUser() method. Is there a reason for this?
- For Clean Architecture and SOLID principles, we should work to refactor the code so that each package is in a Clean Architecture layer folder - but this can be completed later when we do code refactoring.

Other than this, the code looks good to me!

**Review by penguinc00kies — CHANGES_REQUESTED** [review]
Hey Dina and Selin,

This is overall well-written code, some things I noticed are:
-good adherence to clean architecture and SOLID principles
-docstrings are clear and concise
-on line 13 of UserAccountList.java, shouldn't it be `private final Map<String, User> useraccountlist = new HashMap<String, User>();` instead?
-in UserCreationController, `java.time.LocalDateTime` is imported but never used
-comments are placed at relevant locations
Good work!

**Comment by DinaLojpur** [comment]
Hello everybody, I have changed my code according to your feedback:
- In src/main/java/user_creator/UserCreator.java, I have added comments explaining why the nested if statement is necessary and what it is doing
- In UserCreationController, I have removed java.time.LocalDateTime as it is never used
- I have decided to keep birthday as a String instead of changing it to a Java Date object as per discussed in our last meeting

User-creation is now ready to be merged to main!

**Review by penguinc00kies — APPROVED** [review]
Looks great! Approved!

**Comment by elsiezhu** [comment]
Hi Dina! Changes look great, request approved!

**Review by elsiezhu — APPROVED** [review]

**Comment by elsiezhu** [comment]
Changes look great Dina! Request approved

**Review by VangoCode — APPROVED** [review]
The changes look good, approved!

**Pull request merged**
