### PR TITLE
refactor-user-creation-and-user-entity-test

### LINKED ISSUE #52: refactor-user-creation-and-user-entity-tests
I am refactoring the user creation and user entity tests.

### PR DESCRIPTION
**Pull request by DinaLojpur**
The user entity and user creator tests have been refactored and are now able to run.

### CODE REVIEW

**Review by selintasman — DISMISSED** [review]
Hey Dina! Good Work! Approved!

**Review by penguinc00kies — APPROVED** [review]
Thanks for catching this oversight Dina! Approved!

**Review by AubreyNadler — APPROVED** [review]
Good

**Review by elsiezhu — APPROVED** [review]
Changes to the test suite looks good! Approved

**Pull request merged**
