### PR TITLE
[refactor-packages-clean-architecture] Refactoring of files completed

### LINKED ISSUE #20: refactor-packages-clean-architecture
This is a refactoring of the file structure to ensure that they are sorted according to their places in the Clean Architecture.
**NOTE FOR TAs!!!!! THIS WAS DONE AS A GROUP ON A LIVE CALL**

### PR DESCRIPTION
**Pull request by elsiezhu**
As a group, we have refactored our files in a way that adheres to Clean Architecture by organizing files into packages. As a result, 4 packages were created - `entities`, `use_cases`, `screens`, and `controllers`.
Just to be clear to the TAs, we (the group) did this **together** on a call.

### CODE REVIEW

**Review by penguinc00kies — APPROVED** [review]
Approved! (Was present when all refactoring was done on Elsie's computer)

**Review by VangoCode — APPROVED** [review]
HI GINA I WAS IN THIS MEETING!👋
looks good Elsie, I approved it

**Review by DinaLojpur — APPROVED** [review]
Hello, I was present in this meeting and all changes have been approved!!

**Review by selintasman — APPROVED** [review]
Everything looks good! (I was present in the meeting when we all refactored the code). Good Job guys!

**Review by AubreyNadler — APPROVED** [review]
Looks good. I was there when we did this btw

**Pull request merged**
