### PR TITLE
[data-predict] Predictor, CaloriePredictor, PredictManager, BMIPredictor, WeightPredictor completed

### LINKED ISSUE #9: data-predict
Feature “Predict data” user story

### PR DESCRIPTION
**Pull request by VangoCode**
This feature is for the backend to generate predictions using each of the Predictor classes.
**Note that BMIPredictor, WeightPredictor, and PredictManager are not _fully_ implemented. They work and have almost all of the functionality finished, but some parts are unfinished due to Aubrey's situation. The full implementation will be written in a new issue.**

Changes:
- Created skeleton classes for `src/main/java/predictor/BMIPredictor.java` and `src/main/java/predictor/WeightPredictor.java` (it's completely implemented except for the actual calculations, right now it just returns an empty/default value)
- Implemented `src/main/java/predictor/CaloriePredictor.java`
- Implemented `src/main/java/predictor/PredictManager.java`
- Created an abstract class for the Predictors in `src/main/java/predictor/Predictor.java`
- Created an empty test suite with skeleton tests in `src/test/java/predictor/BMIPredictorTest.java`
- Created and implemented test suite for CaloriePredictor in `src/test/java/predictor/CaloriePredictorTest.java`
- Created an empty test suite with skeleton tests in `src/test/java/predictor/PredictManagerTest.java`
- Created an empty test suite with skeleton tests in `src/test/java/predictor/WeightPredictorTest.java` aside from the very first test, which has been implemented

### CODE REVIEW

**Review by DinaLojpur — CHANGES_REQUESTED** [review]
Hello Ron, your code looks great! I just have a couple of comments/suggestions:
- Considering Aubrey's absence, you've done a commendable job at spearheading this use case. Your in-depth explanations for the unfinished methods really help visualize what the future code will execute.
- When writing docstrings, use "/**" instead of "/*" (which is meant for multi-line comments). That way you can add the parameter and return explanations as well.
- In src/main/java/predictor/CaloriePredictor.java, the calculateCalories method is returning a float value. Consider changing the return type to a double, since we've all been using doubles in our code!
- The test files are missing some tests, just make sure you don't forget to fill them in later on.

Great job!

**Review by selintasman — CHANGES_REQUESTED** [review]
Hi Ron! Your code looks great so far! Given the circumstances, it is clear you have made significant contribution to your feature. A couple comments and suggestions that I have are:
- In CaloriePredictor.java, I believe it would be better if the return type of the method calculateCalories is double instead of a float so that it is more consistent with the rest of your code.
- Please consider using /** instead of /* for your docstrings.
- Lastly, please don't forget to fill in the test files since they are empty so far.

Otherwise everything else looks good to me!

**Comment by VangoCode** [comment]
Hi @selintasman @DinaLojpur , thank you both for your reviews! I have made changes to my code to reflect your requests, please let me know if it's okay to merge now!

**Review by penguinc00kies — APPROVED** [review]
Hello Ron, 

Your code is overall very well-written! 
-you clearly label which class belongs to which layer in clean architecture as well as have very detailed docstrings
-is there any particular reason why the abstract class Predictor within Predictor.java is an abstract class and not an interface?
-your test suite is very comprehensive
-although you have a lot of TODOs, it is understandable in light of Aubrey's unfortunate circumstances

**Comment by VangoCode** [comment]
Hi @penguinc00kies , thanks for your review! I chose to make Predictor an abstract class instead of an interface because each Predictor is very closely related. Since WeightPredictor and BMIPredictor are both doing predictions, and the only change is _what_ they are predicting, I decided that they are closely enough related that I should use an abstract class, rather than using an interface, which is used for many methods that require some type of functionality.

**Review by selintasman — APPROVED** [review]
Hi Ron thank you for the changes!

**Review by DinaLojpur — APPROVED** [review]
All the changes look good!

**Pull request merged**
